AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ryancdkparamextension:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::494656045728:role/ParameterStoreExtensionSt-functionServiceRoleEF216-1BUGA2T81SOGF
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
          PARAMETERS_SECRETS_EXTENSION_LOG_LEVEL: DEBUG
          PARAM_NAME: CFN-AParameter7619EE27-vAceXP7oUwby
      Layers:
        - >-
          arn:aws:lambda:eu-west-1:015030872274:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
